version: "3.0"
services:
  webserver:
    container_name: nginx_server
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: ./.docker/workspace/Dockerfile
    volumes:
      - ./src:/var/www/html
    tty: true
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
