version: "3.0"
services:
  webserver:
    container_name: laravel_nginx
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      laravel:
  php-fpm:
    container_name: laravel_fpm
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
      - .docker/php:/usr/local/etc/php-fpm.d
    networks:
      laravel:
  workspace:
    container_name: laravel_workspace
    build:
      context: .
      dockerfile: .docker/workspace/Dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    tty: true
    networks:
      laravel:
  mysql:
    container_name: laravel_mysql
    image: mysql:8.0
    volumes:
      - .docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
    networks:
      laravel:
networks:
  laravel:
