version: "3.0"
services:
  webserver:
    container_name: laravel_nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      laravel:
  php-fpm:
    container_name: laravel_fpm
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      laravel:
  workspace:
    container_name: laravel_workspace
    build:
      context: .
      dockerfile: ./.docker/workspace/Dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    tty: true
    networks:
      laravel:
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
    networks:
      laravel:
networks:
  laravel:
