version: "3.0"
services:
  webserver:
    container_name: nginx_server
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - php-fpm
      - composer
      - npm
      - mysql
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: ./.docker/workspace/Dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php-fpm
      - composer
      - npm
    tty: true
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    tty: true
    environment:
      MYSQL_DATABASE: demo
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: secret
    user: 1000:1000
  composer:
    container_name: composer
    build:
      context: .
      dockerfile: ./.docker/composer/Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on: 
      - php-fpm
    tty: true
  npm:
    container_name: npm
    image: node:14.16.1-alpine3.13
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    tty: true